Create task crossref
scieloorg/scms-oca pull request #179
Opened 2023-03-27 13:28 UTC by samuelveigarangel

#### O que esse PR faz?
Cria task para extrair dados da API Crossref e salva esse dados no banco de dados.

#### Onde a revisão poderia começar?
Pelo commit.

#### Como este poderia ser testado manualmente?
Pela interface do admin em tarefas.

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
[#161](https://github.com/scieloorg/scms-oca/issues/161)

### Referências
[Ref.1](https://github.com/CrossRef/rest-api-doc#filter-names) [Ref.2](https://github.com/Crossref/rest-api-doc/blob/master/api_format.md) [Ref.3](https://thetldr.tech/when-to-use-update_or_create-in-django/)

2023-03-27 14:55 UTC, gitnnolabs commented
Validando...

2023-03-27 15:34 UTC, gitnnolabs requested changes

2023-03-27 15:34 UTC, gitnnolabs commented on requirements/base.txt
> +orjson==3.8.7  # https://github.com/ijl/orjson
👍

2023-03-27 15:34 UTC, gitnnolabs commented on requirements/local.txt
> +# psycopg2==2.9.3  # https://github.com/psycopg/psycopg2
@samuelveigarangel poderia por gentileza remover esse linha comentada?

2023-03-27 15:34 UTC, gitnnolabs commented on scholarly_articles/choices.py
> +    ("CROSSREF", "CROSSREF"),
👍

2023-03-27 15:34 UTC, gitnnolabs commented on scholarly_articles/crossref/fetch_data_retry.py
> +def fetch_data(url, headers=None, json=False, timeout=2, verify=True):
@samuelveigarangel se entendi acho que não estamos utilizando esse função correto?

2023-03-27 15:34 UTC, gitnnolabs commented on scholarly_articles/tasks.py
> +    url = f'https://api.crossref.org/works?query.affiliation=Brazil&filter=type:journal-article,from-update-date:{from_update_date},until-update-date:{until_update_date}&cursor=*'
Seria interessante que o endereço da API seja algo configurável por variável de ambiente no arquivo de configuração ``base.py``. 

``https://api.crossref.org/works``

2023-03-27 15:34 UTC, gitnnolabs commented on scholarly_articles/tasks.py
> +    Retrieves article data from CrossRef API for a given range of years.
Seria interessante documentar o **formato da resposta do crossref** aqui para que possamos entender melhor a lógica que está iterando sobre os dados.

2023-03-27 15:34 UTC, gitnnolabs commented on scholarly_articles/tasks.py
> +    dados = ['DOI', 'title', 'volume', 'publisher', 'source', 'type',]
@samuelveigarangel é necessário que tenhamos o **autores** do artigo. Na API do crossref temos esse dado e não obrigatório para o negócio. 

API doc crossref: 

<img width="920" alt="Screenshot 2023-03-27 at 12 23 21" src="https://user-images.githubusercontent.com/86991526/227987542-4d0d2edc-852c-4bef-9a02-c8109539ae67.png">

Modelo do scholarly_articles: https://github.com/scieloorg/scms-oca/blob/bd14c214c2fc94b5ad2389753f31b5973034a957/scholarly_articles/models.py#L36

Item para journal precisamos do periódico do artigo também. 

Modelo do scholarly_articles: https://github.com/scieloorg/scms-oca/blob/bd14c214c2fc94b5ad2389753f31b5973034a957/scholarly_articles/models.py#L148

Dado no crossref: 
<img width="755" alt="Screenshot 2023-03-27 at 12 32 14" src="https://user-images.githubusercontent.com/86991526/227989548-9c5b48ec-3553-422c-865f-2620ee314783.png">

2023-03-27 15:34 UTC, gitnnolabs commented on scholarly_articles/tasks.py
> +                if not data['message']['items']:
Não entendi nesse laço o momento que ele para!

2023-03-27 16:49 UTC, samuelveigarangel commented on scholarly_articles/tasks.py
> +                if not data['message']['items']:
De acordo com a documentação, o cursor deveria parar quando não há mais itens a serem percorridos no JSON. No entanto, observei que, mesmo depois de exibir todos os itens, o cursor continua avançando. Para resolver esse problema, adicionei uma condição "if" para verificar se há mais itens a serem exibidos. Se não houver mais itens, a execução da tarefa é interrompida. Para verificar isso, utilizei os anos de 2012- 2012. URL: https://api.crossref.org/works?query.affiliation=Brazil&filter=type:journal-article,from-update-date:2012,until-update-date:2012&cursor=*

2023-03-27 16:51 UTC, samuelveigarangel commented on scholarly_articles/crossref/fetch_data_retry.py
> +def fetch_data(url, headers=None, json=False, timeout=2, verify=True):
Não, vou tira-la do código.

2023-03-27 16:57 UTC, samuelveigarangel commented on scholarly_articles/tasks.py
> +    dados = ['DOI', 'title', 'volume', 'publisher', 'source', 'type',]
Então, acho que em relação ao nome do titulo do Journal, é o publisher. Inserido no array. [Ref](https://github.com/Crossref/rest-api-doc/blob/master/api_format.md)

2023-03-28 10:35 UTC, gitnnolabs commented on scholarly_articles/tasks.py
> +    dados = ['DOI', 'title', 'volume', 'publisher', 'source', 'type',]
@samuelveigarangel 

O nome do publicador é diferente do nome do periódico. 

Publicador é que realiza a publicação nesses casos geralmente é o SciELO, mas o journal é que faz todo o fluxo para antes de publicação e "confecciona" a revista.

São diferentes, no caso da imagem que te mandei acima o periódico é **Revista IBRACON** e o publicador é o **SciELO**.

2023-03-28 10:41 UTC, gitnnolabs commented on scholarly_articles/tasks.py
> +                if not data['message']['items']:
Irei após os ajustes realizar um testes de execução!

2023-03-28 15:22 UTC, gitnnolabs commented
Realizando uma validação de execução....

2023-03-28 18:15 UTC, gitnnolabs commented
@samuelveigarangel 

Para rodar a implementação deu os seguintes erros: 

Ao criar uma task: 

![Screenshot 2023-03-28 at 15 09 40](https://user-images.githubusercontent.com/86991526/228330562-339ea58c-3faa-44d9-9bb2-dde6f98dd338.png)

Ao tentar executar a tarefa: 
![Screenshot 2023-03-28 at 15 13 16](https://user-images.githubusercontent.com/86991526/228330578-78427962-9152-45ba-8a5a-4c9d5589c70c.png)

2023-03-28 18:18 UTC, gitnnolabs commented
@samuelveigarangel 

Chegou a rodar localmente essa task?

2023-03-28 18:31 UTC, gitnnolabs commented on scholarly_articles/crossref/crossref.py
> +                defaults={
Se entendi ainda não está salvando os autores e o periódico, correto?

2023-03-28 19:03 UTC, samuelveigarangel commented on scholarly_articles/crossref/crossref.py
> +                defaults={
Correto,

2023-03-31 10:30 UTC, gitnnolabs commented
@samuelveigarangel 

Realizando uma nova rodada de testes....

2023-04-05 12:14 UTC, merged