Adapt indicators
scieloorg/scms-oca pull request #74
Opened 2022-09-23 21:07 UTC by Rossi-Luciano

#### O que esse PR faz?
Modifica o modela de indicadores de acordo com as especificações fornecidas.

#### Onde a revisão poderia começar?
Por commit.

#### Como este poderia ser testado manualmente?
NA.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
![image](https://user-images.githubusercontent.com/41302084/192056368-b88e584d-1bfa-4c04-808a-76f28c7439c5.png)

#### Quais são tickets relevantes?
NA.

### Referências
[Definições](https://drive.google.com/drive/folders/1_J8iKhr_gayuBqtvnSWreC-eBnxzY9rh)

2022-09-25 17:16 UTC, robertatakenaka commented on indicator/models.py
> +    geographic_context = models.ForeignKey(Location, verbose_name=_("Geographic context"), on_delete=models.SET_NULL,
@Rossi-Luciano faltou ano (s) - cronológico

2022-09-25 17:16 UTC, robertatakenaka commented on indicator/wagtail_hooks.py
> +    menu_label = _('Indicator Directory')  # ditch this to use verbose_name_plural from model
@Rossi-Luciano acho que fica como indicadores mesmo

2022-09-26 11:24 UTC, gitnnolabs commented on indicator/models.py
> +        return u'%s - (%s / %s)' % (self.record_status, self.previous_record, self.posterior_record)
Como os campos podem ser vazio, sugiro que seja validado a existências dele para compor o nome do objeto, basicamente adicionar ifs para validar a existência.

2022-09-26 11:25 UTC, gitnnolabs commented on indicator/models.py
> +class Post(CommonControlField):
Não entendi a ideia dessa classe! @Rossi-Luciano seria possível adicionar um comentário descrevendo-a.

2022-09-26 11:59 UTC, Rossi-Luciano commented on indicator/models.py
> +    geographic_context = models.ForeignKey(Location, verbose_name=_("Geographic context"), on_delete=models.SET_NULL,
Adicionei o campo para data.

2022-09-26 12:00 UTC, Rossi-Luciano commented on indicator/wagtail_hooks.py
> +    menu_label = _('Indicator Directory')  # ditch this to use verbose_name_plural from model
Corrigido.

2022-09-26 12:00 UTC, Rossi-Luciano commented on indicator/models.py
> +        return u'%s - (%s / %s)' % (self.record_status, self.previous_record, self.posterior_record)
Corrigido.

2022-09-26 14:42 UTC, robertatakenaka commented on indicator/choices.py
> +)
@Rossi-Luciano no caso, a lista terá que conter os classification de todos os 4 choices, um de cada diretório.

2022-09-26 14:45 UTC, robertatakenaka commented on indicator/choices.py
> +)
Então, você pode importar todos os choices e somar:
```python
from infrastructure_directory.choices import classification as INFRA_CLASSIFICATION
from event_directory.choices import classification as EVENT_CLASSIFICATION

classification = list(EVENT_CLASSIFICATION) + list(INFRA_CLASSIFICATION)
```

2022-09-26 14:51 UTC, robertatakenaka requested changes
Veja comentário sobre classification

2022-09-26 19:47 UTC, merged