Set country
scieloorg/scms-oca pull request #99
Opened 2022-10-25 19:38 UTC by Rossi-Luciano

#### O que esse PR faz?
Tenta identificar o país de origem de um contribuidor, a partir do nome declarado de sua afiliação.

#### Onde a revisão poderia começar?
Por commit.

#### Como este poderia ser testado manualmente?
Executar 'set_country.py' pelo terminal:
`python3 manage.py runscript set_country`
É preciso carregar os exemplos de registros antecipadamente (pode ser feito pela interface)

#### Algum cenário de contexto que queira dar?
Apesar de exitir, no arquivo `countries.csv`, os atributos `Capital`, `Código ISO (3 letras)` e `Código ISO (2 letras)` eles não foram úteis, a princípio, para a identificação do país (podem ser aproveitados considerando outra estratégia).

### Screenshots
![image](https://user-images.githubusercontent.com/41302084/197865471-27f08a1b-8d63-4666-9bd9-5aa863b0159a.png)

#### Quais são tickets relevantes?
NA. 

### Referências
NA.

2022-10-25 22:22 UTC, robertatakenaka commented on scholarly_articles/scripts/set_country.py
> +    return models.Affiliations.objects.filter(name__icontains=country)
substituir isso por:
```python
return models.Affiliations.objects.filter(name__icontains=country, country__isnull=True)
```

2022-10-25 22:23 UTC, robertatakenaka commented on scholarly_articles/scripts/set_country.py
> +                    if not affiliation.country:
@Rossi-Luciano esta linha pode ser eliminada

2022-10-25 22:24 UTC, robertatakenaka commented on scholarly_articles/scripts/set_country.py
> +                        affiliation.country = name_pt
@Rossi-Luciano preencher country com o objeto do país

2022-10-25 22:28 UTC, robertatakenaka commented on scholarly_articles/scripts/set_country.py
> +    with open(os.path.dirname(os.path.realpath(__file__)) + "/../fixtures/countries.csv", 'r') as fp:
@Rossi-Luciano há os modelos para City, State, Country. Criar bulk_country. Mas antes criar mais campos no modelo Country. 
https://github.com/scieloorg/scms-oca/blob/af7c117a05235667d1ce39de2d4f8e14e8eaea69/usefulmodels/models.py#L140

2022-10-26 21:42 UTC, robertatakenaka commented on usefulmodels/scripts/bulk_countries.py
> +            models.Country(name_pt=name_pt, name_en=name_en, acronym=acron3, creator=creator).save()
criar com acron2 também

2022-10-26 21:42 UTC, robertatakenaka commented on usefulmodels/models.py
>      acronym = models.CharField(_("Acronym to the Country"), blank=True, null=True, max_length=255)
adicionar acron2

2022-10-26 21:43 UTC, robertatakenaka commented on scholarly_articles/scripts/set_country.py
> +                    affiliation.save()
vou sugerir um código

2022-10-26 21:46 UTC, robertatakenaka commented on scholarly_articles/scripts/set_country.py
> +                    affiliation.save()
```python
from django.db.models import Q


for country in Country.objects.all():
    for aff in models.Affiliations.objects.filter(
            Q(name__icontains=country.name_pt) | Q(name__icontains=country.name_en),
            country__isnull=True).iterator():
        aff.country = country
        aff.save()
```

2022-10-26 21:52 UTC, robertatakenaka requested changes
fazer mudanças conforme sugestões

2022-10-27 13:59 UTC, robertatakenaka commented on usefulmodels/models.py
> -    acronym = models.CharField(_("Acronym to the Country"), blank=True, null=True, max_length=255)
@Rossi-Luciano mantenaha o `acronym`, pois ele deve estar sendo usado

2022-10-28 11:43 UTC, gitnnolabs commented
@Rossi-Luciano @robertatakenaka 

Estou validando...

2022-10-28 12:26 UTC, gitnnolabs commented
@Rossi-Luciano 

Em conversa com a @robertatakenaka verifiquei que é possível termos o atributos Capital, Código ISO (3 letras) e Código ISO (2 letras) no modelo de country!

2022-10-31 11:01 UTC, gitnnolabs commented
@Rossi-Luciano 

Estou avaliando esse PR.

2022-10-31 11:25 UTC, robertatakenaka approved these changes

2022-10-31 11:50 UTC, merged